# Generated by Django 4.1.1 on 2022-09-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("inquiry_txt", models.TextField()),
                ("add_time", models.DateTimeField()),
            ],
        ),
    ]
