# Generated by Django 4.1.1 on 2022-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covid", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="add_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
